### ISSUE TITLE
Switch to ndx-events==0.3.0 ?

### ISSUE THREAD

**Issue by weiglszonja** [catalystneuro/lerner-lab-to-nwb#31]
`ndx-events` has a newer version (not released on pypi yet), it introduces new objects for storing events data: https://github.com/rly/ndx-events/blob/main/src/spec/create_extension_spec.py

I noticed you're using the "older" version:
https://github.com/catalystneuro/lerner-lab-to-nwb/blob/c5135ca11a9b47ba3c579bcc3ac2c8a002597ddd/frozen_dependencies.txt#L90

With @alessandratrapani we both updated to 0.3.0, I think we should be aligned in this as well and use the latest version of `ndx-events`. What do you think? 

(The neurosift visualisation plugin issue would be also dissolved once you're using 0.3.0, see [this file](https://neurosift.app/?p=/nwb&url=https://api.dandiarchive.org/api/assets/a07e739d-6246-4f76-8649-9a345cfbdda7/download/&dandisetId=001038&dandisetVersion=draft&tab=neurodata-item:/processing/behavior/WheelEvents|EventsTable) for example)

**Comment by pauladkisson** [comment]
Thank you for brining this to my attention!

This is a fairly substantial change for a conversion that is just about done, but the neuroconv MedPCInterface will definitely want to use the latest ndx-events, so I guess it's worth going for here...

**Comment by pauladkisson** [comment]
After thinking about it some more, and playing around with the new ndx-events, I think this conversion is too far along to warrant taking all the time to update to a new data structure.  Plus, ndx-events 0.3.0 isn't even published on pypi yet and there's not yet good docs for it.  With that in mind, I think we should continue using 0.2.0 for this conversion, and I will update the MedPCInterface on neuroconv whenever 0.3.0 releases properly.

**Comment by weiglszonja** [comment]
Okay sure, just letting you know. Hope we’ll get a new release for ndx-events soon :)
