### ISSUE TITLE
don't assume timezone

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/lerner-lab-to-nwb#4]
https://github.com/catalystneuro/lerner-lab-to-nwb/blob/856b798dcf353dfaf7ec7ea6fa468ed6111dcb36/src/lerner_lab_to_nwb/seiler_2024/seiler_2024behaviorinterface.py#L70

This may be correct for this particular lab conversion, but even so I'd rather not include this assumption in the interface. This class should return the session_start_time without a timezone, and the timezone can be set in an outer scope, e.g. in the Converter object or even in the convert_sessions.py file

**Comment by pauladkisson** [comment]
Is this a best practice? What exactly is the advantage of setting the time zone in the outer scope?

**Comment by CodyCBakerPhD** [comment]
It's explicit that way

Otherwise you assume they have it set correctly on the machine
